package com.example.sayit.core.localization

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val installmentDeletedFeedback: String = "تم حذف خطة التقسيط",
    val paymentRecordedFeedback: String = "تم تسجيل الدفعة بنجاح",
    val installmentAddedFeedback: String = "تمت إضافة خطة التقسيط بنجاح",
    val settingsPleaseEnableNotificationAccessInSettings: String = "يرجى تفعيل صلاحية قراءة الإشعارات من إعدادات الهاتف",
    val settingsAIAssistantActiveReady: String = "المساعد الذكي نشط ومفعل تلقائياً",
    val settingsRealConversationalAIFinancialAdvisor: String = "شات بوت ذكي حقيقي لتحليل المصاريف والاستشارات",
    val settingsAICompanion: String = "المساعد المالي الذكي",
    val settingsYouAreUsingTheLatestVersionOf: String = "أنت تستخدم أحدث إصدار متاح من Say It! ✅",
    val settingsCheckNow: String = "فحص الآن",
    val settingsStartTour: String = "بدء الجولة",
    val settingsTakeAQuickInteractiveWalkthroughOfAll: String = "تعرّف على أهم مزايا ومساعدات التطبيق خطوة بخطوة",
    val settingsInteractiveGuideTour: String = "الجولة الإرشادية للتطبيق",
    val settingsDarkMode: String = "🌙 الوضع الداكن",
    val settingsLightMode: String = "☀️ الفاتح (الأبيض)",
    val settingsChooseBetweenCrispLightThemeAndSleek: String = "التبديل بين المظهر الفاتح (الأبيض) والوضع الداكن",
    val settingsAppAppearance: String = "مظهر التطبيق",
    val quickLunch: String = "🍽️ غداء",
    val quickGroceries: String = "🛒 بقالة",
    val quickTransit: String = "🚗 مواصلات",
    val quickCoffee: String = "☕ قهوة",
    val uiSavePlan: String = "حفظ الخطة",
    val uiPleaseEnterMonthsDuration: String = "يرجى تحديد عدد الشهور",
    val uiPleaseEnterAValidMonthlyAmount: String = "يرجى تحديد القسط الشهري بشكل صحيح",
    val uiPleaseEnterInstallmentName: String = "يرجى كتابة اسم القسط",
    val uiNotesOptional: String = "ملاحظات إضافية (اختياري)",
    val uiDueDay: String = "يوم الاستحقاق",
    val uiItemInstallmentName: String = "اسم القسط / الغرض (مثال: هاتف جديد، سيارة)",
    val uiAddNewInstallmentPlan: String = "إضافة خطة تقسيط جديدة",
    // ── Language flag (explicit, not derived from currency) ──
    val isArabic: Boolean = true,

    // TopBar & Header
    val appName: String,
    val localOfflineBadge: String,
    val morningGreeting: String,
    val eveningGreeting: String,
    val dashboardSubtitle: String,
    val shareReport: String,
    val exportCsv: String,
    val languageToggle: String,

    // Navigation Tabs
    val tabDashboard: String,
    val tabAnalytics: String,
    val tabInstallments: String,
    val tabAiCopilot: String = "المساعد",
    val tabSqlDb: String,
    val tabSettings: String,

    // Actions & Common
    val addManual: String,
    val voiceRecord: String,
    val edit: String,
    val delete: String,
    val close: String,
    val cancel: String,
    val save: String,
    val saveChanges: String,
    val confirm: String,
    val apply: String,
    val currency: String,
    val perDay: String,
    val all: String,

    // Budget Summary Card
    val monthlyBudget: String,
    val smartRemainingBudget: String,
    val remainingCurrency: String,
    val dailyBurnRate: String,
    val depletionDate: String,
    val spent: String,
    val budgetCap: String,
    val startSetBudget: String,
    val startSetBudgetDesc: String,
    val setBudgetNow: String,
    val totalSpentLabel: String,

    // Cashflow Row
    val income: String,
    val expenses: String,
    val netSavings: String,
    val totalInflow: String,
    val totalOutflow: String,
    val savings: String,
    val savingsRate: String,

    // Time Periods
    val periodThisMonth: String,
    val periodLastMonth: String,
    val periodLast30Days: String,
    val periodAllTime: String,

    // Transactions List & Empty State
    val searchPlaceholder: String,
    val transactionsHistory: String,
    val noTransactions: String,
    val noTransactionsDesc: String,
    val today: String,
    val yesterday: String,
    val transactionSingle: String,
    val transactionPlural: String,

    // Transaction Details & Dialogs
    val transactionDetails: String,
    val editTransaction: String,
    val addTransactionTitle: String,
    val expenseType: String,
    val incomeType: String,
    val amountLabel: String,
    val amountPlaceholder: String,
    val merchantLabel: String,
    val merchantPlaceholder: String,
    val notesLabel: String,
    val categoryLabel: String,
    val paymentMethodLabel: String,
    val sourceLabel: String,
    val dateTimeLabel: String,
    val rawTextLabel: String,

    // Analytics Screen
    val runwayTitle: String,
    val runwaySubtitle: String,
    val zeroBudgetNotice: String,
    val overBudget: String,
    val fullBudget: String,
    val budgetConsumed: String,
    val projectedMonthTotal: String,
    val spendingByCategory: String,
    val noExpensesForCategories: String,
    val topMerchants: String,
    val noMerchantsYet: String,

    // Settings & Bank Hub
    val monthlyBudgetHeading: String,
    val budgetHeadingDesc: String,
    val notSpecified: String,
    val customBudgetLabel: String,
    val customBudgetPlaceholder: String,
    val smsSyncTitle: String,
    val smsSyncDesc: String,
    val smsSyncButton: String,
    val permissionsTitle: String,
    val smsPermissionTitle: String,
    val smsPermissionDesc: String,
    val notifPermissionTitle: String,
    val notifPermissionDesc: String,
    val openNotifSettings: String,
    val devOptionsTitle: String,
    val devOptionsDesc: String,
    val devModeActive: String,
    val lockDevMode: String,
    val languageTitle: String,
    val languageDesc: String,

    // Accessibility Labels (a11y)
    val voiceInputDesc: String = "تسجيل صوتي",
    val sendMessageDesc: String = "إرسال رسالة",
    val backDesc: String = "رجوع",
    val clearChatDesc: String = "مسح المحادثة",
    val clearChatConfirmTitle: String = "مسح المحادثة؟",
    val clearChatConfirmMessage: String = "هل تريد مسح كل الرسائل والبدء من جديد؟",

    // Installments & Debts
    val installmentsTitle: String = "الأقساط والمديونيات",
    val installmentsSubtitle: String = "إدارة الأقساط ومسار التصفير",
    val addInstallment: String = "إضافة قسط",
    val activeInstallments: String = "النشطة",
    val completedInstallments: String = "المكتملة",
    val monthlyObligations: String = "الالتزام الشهري",
    val totalDebtRemaining: String = "إجمالي المتبقي",
    val noInstallmentsFound: String = "لا توجد أقساط مسجلة",
    val recordPayment: String = "سداد قسط",
    val payoffProgress: String = "مسار التصفير",
    val installmentName: String = "اسم القسط / السلعة",
    val providerLabel: String = "الجهة / البنك",
    val monthlyAmountLabel: String = "القسط الشهري",
    val totalAmountLabel: String = "المبلغ الإجمالي",
    val durationMonthsLabel: String = "المدة بالأشهر",
    val startDateLabel: String = "تاريخ البداية",
    val deleteInstallmentConfirm: String = "حذف القسط",
    val deleteInstallmentMessage: String = "هل أنت متأكد من حذف هذا القسط وسجلاته؟",
    val dueThisMonth: String = "مستحق هذا الشهر",
    val paidThisMonth: String = "تم سداد هذا الشهر",
    val overdue: String = "متأخر",
    val upcomingInstallmentNotice: String = "أقساط قادمة هذا الأسبوع",
    val viewAllInstallments: String = "عرض كل الأقساط",

    // Installments – NEW keys (Phase 1 i18n)
    val monthFullySettled: String = "تم سداد الشهر بالكامل",
    val plansCount: String = "خطط",
    val paidLabel: String = "المسدد",
    val totalLabel: String = "الإجمالي",
    val monthInstallmentPaid: String = "تم سداد قسط هذا الشهر",
    val partiallyPaidFormat: String = "مدفوع جزئياً: %s من %s %s",
    val unpaidDueFormat: String = "مستحق: %s %s (يوم %d)",
    val payButton: String = "تسجيل سداد",
    val deleteInstallmentDesc: String = "حذف القسط",
    val debtPayoffCurve: String = "مسار التخلص من المديونية",
    val projectedZeroDebt: String = "تناقص الأقساط حتى التصفير التام",
    val debtFreeLabel: String = "خالي من الديون",
    val payoffLabel: String = "اكتمال",
    val noDebtCongrats: String = "تهانينا، لا توجد أقساط أو مديونيات متبقية 🎉",
    val addFirstPlanPayoff: String = "أضف قسطك الأول لبدء حساب مسار التصفير",
    val paidSoFarLabel: String = "المسدد حتى الآن",

    // Record Payment Dialog – NEW keys
    val recordInstallmentPayment: String = "تسجيل سداد القسط",
    val thisMonthDue: String = "قسط هذا الشهر:",
    val paidSoFarColon: String = "تم سداده حتى الآن:",
    val remainingToSettle: String = "المتبقي للاكتمال:",
    val payFullInstallmentFormat: String = "سداد القسط بالكامل (%s %s)",
    val customPaymentAmount: String = "أو حدد المبلغ المدفوع (سداد جزئي أو كامل)",
    val invalidAmountError: String = "يرجى إدخال مبلغ صحيح",
    val confirmPayment: String = "تأكيد السداد",

    // Dashboard Installments Card – NEW keys
    val activePlansPayoffTracking: String = "%d خطط نشطة | مسار التصفير التلقائي",
    val smartDebtTracker: String = "تتبع أقساطك والمديونيات بذكاء",
    val addFirstPlanDashboard: String = "أضف خطتك الأولى لحساب مسار التصفير ورصد الـ SMS",
    val dueThisMonthLabel: String = "المتبقي هذا الشهر",
    val paidAmountFormat: String = "مسدد: %s %s",

    // Quick Presets – NEW keys
    val quickTapLogTitle: String = "تسجيل سريع بنقرة واحدة ⚡",
    val customAdd: String = "مخصص +",

    // Splash Screen – NEW keys
    val splashTagline: String = "مستشارك المالي الذكي ومحفظتك الآمنة",
    val splashPillOffline: String = "أوفلاين 100%",
    val splashPillAi: String = "ذكاء مصري",
    val splashPillBanks: String = "انستاباي وبنوك",
    val splashEncryptedMessage: String = "مشفر ومحفوظ محلياً على جهازك",

    // App Update – NEW keys
    val newUpdateAvailable: String = "🚀 تحديث جديد متوفر",
    val newVersionReady: String = "إصدار جديد متوفر الآن",
    val currentVersionFormat: String = "الحالي: v%s",
    val whatsNewTitle: String = "ما الجديد في هذا الإصدار:",
    val downloadingFormat: String = "جاري التحميل... %d%%",
    val cancelDownload: String = "إلغاء التحميل",
    val downloadFinished: String = "تم تحميل التحديث بنجاح! جاهز للتثبيت 📦",
    val installUpdateNow: String = "تثبيت التحديث الآن 📦",
    val downloadFailed: String = "تعذر تنزيل التحديث",
    val browserButton: String = "المتصفح",
    val retryButton: String = "إعادة المحاولة",
    val updateDownloadNow: String = "تحديث وتنزيل الآن 🚀",
    val laterButton: String = "لاحقاً",

    // Bank Hub Updates Section – NEW keys
    val appUpdatesTitle: String = "التحديثات",
    val currentVersionLabel: String = "الإصدار الحالي: v%s",
    val checkingForUpdates: String = "جاري الفحص...",
    val checkForUpdates: String = "فحص التحديثات الآن",
    val upToDate: String = "✅ أنت على أحدث إصدار!",

    // Analytics Comparison
    val vsLastMonth: String = "مقارنة بالشهر السابق",
    val spendingIncrease: String = "زيادة في الصرف",
    val spendingDecrease: String = "توفير في الصرف"
)

val LocalStrings = staticCompositionLocalOf<AppStrings> {
    error("No AppStrings provided. Please provide via CompositionLocalProvider.")
}
